//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kii.odbConnectHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int Id { get; set; }
        public System.DateTime date1 { get; set; }
        public System.DateTime date2 { get; set; }
    }
}
