//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kii.odbConnectHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string GroupName { get; set; }
        public System.DateTime Data { get; set; }
        public int IdStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual User User { get; set; }
    }
}
